import Head from "next/head";
import Layout1 from "../components/layout/layout";

import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<Layout1>
			<Head>
				<title>Dummy-ecom</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}></main>
		</Layout1>
	);
}
